"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import MapChooser from "./MapChooser";

export default function BoardEditor({ boardId }) {
  const router = useRouter();
  const [data, setData] = useState(null), [error, setError] = useState(""), [invite, setInvite] = useState(""), [title, setTitle] = useState("");
  const load = async () => { const response = await fetch(`/api/boards/${boardId}`); const body = await response.json(); if (!response.ok) return setError(body.error); setData(body); setTitle(body.board.title); };
  useEffect(() => { load(); }, [boardId]);
  async function act(action, extra = {}) { setError(""); const response = await fetch(`/api/boards/${boardId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); const body = await response.json(); if (!response.ok) return setError(body.error); await load(); }
  async function move(index, offset) { const rows = [...data.places]; const target = index + offset; if (target < 0 || target >= rows.length) return; [rows[index], rows[target]] = [rows[target], rows[index]]; setData({ ...data, places: rows }); await act("reorder", { placeIds: rows.map((place) => place.id) }); }
  async function removeBoard() { if (!confirm("Delete this board permanently?")) return; const response = await fetch(`/api/boards/${boardId}`, { method: "DELETE" }); if (response.ok) router.push("/plan"); else setError((await response.json()).error); }
  if (!data) return <p className="sub">{error || "Loading board…"}</p>;
  return <div className="planner-stack"><section className="card"><span className="eyebrow">Collaborative board</span><div className="details-row"><input value={title} maxLength={80} onChange={(event) => setTitle(event.target.value)} disabled={!data.owner}/>{data.owner && <button className="btn small" onClick={() => act("rename", { title })}>Rename</button>}</div><div className="toggle-row"><div><strong>Public burner link</strong><div className="sub">Anyone with the link can view it without an account.</div></div><input aria-label="Public board" type="checkbox" checked={data.board.is_public} disabled={!data.owner} onChange={(event) => act("publish", { value: event.target.checked })}/></div><button className="btn ghost block" onClick={() => { const shareUrl = `${window.location.origin}/b/${data.board.share_slug}`; return navigator.share ? navigator.share({ title: data.board.title, url: shareUrl }) : navigator.clipboard.writeText(shareUrl); }}>Share board</button></section>
    {data.owner && <section className="card"><h2>Invite a collaborator</h2><p className="sub">Enter their exact Weyn display name. Members can add, remove, reorder, and vote.</p><div className="details-row"><input value={invite} onChange={(event) => setInvite(event.target.value)} placeholder="Display name"/><button className="btn small" disabled={!invite.trim()} onClick={async () => { await act("invite", { displayName: invite }); setInvite(""); }}>Invite</button></div>{data.members.map((member) => <div className="details-row" key={member.user_id}><span>{member.profile?.display_name || "Weyn member"} · {member.role}</span>{member.role === "member" && <button className="btn small ghost" onClick={() => act("removeMember", { userId: member.user_id })}>Remove</button>}</div>)}</section>}
    <section><h2>Vote and order the day</h2>{!data.places.length && <p className="sub">Add places from your planner first.</p>}{data.places.map((place, index) => <div className="card" key={place.id}><div className="details-row"><div><strong>{index + 1}. {place.name}</strong><div className="sub">{place.neighborhood || place.city || "UAE"} · score {place.score}</div></div><MapChooser venue={place} compact/></div><div className="venue-links"><button className={`btn small ${place.myVote === 1 ? "" : "ghost"}`} onClick={() => act("vote", { placeId: place.id, vote: 1 })}>👍</button><button className={`btn small ${place.myVote === -1 ? "" : "ghost"}`} onClick={() => act("vote", { placeId: place.id, vote: -1 })}>👎</button><button className="btn small ghost" onClick={() => move(index, -1)}>↑</button><button className="btn small ghost" onClick={() => move(index, 1)}>↓</button><button className="btn small ghost" onClick={() => act("removePlace", { placeId: place.id })}>Remove</button></div></div>)}</section>
    {data.owner && <button className="btn ghost" onClick={removeBoard}>Delete board</button>}{error && <div className="notice err">{error}</div>}</div>;
}
