"use client";
import { useEffect, useMemo, useState } from "react";
import MapChooser from "./MapChooser";

function coords(p){const a=Number(p.latitude),o=Number(p.longitude);return Number.isFinite(a)&&Number.isFinite(o)?[a,o]:null}
function dist(a,b){const x=coords(a),y=coords(b);if(!x||!y)return 1e9;return Math.hypot(x[0]-y[0],x[1]-y[1]);}
function orderStops(items){if(items.length<2)return items;const left=[...items],out=[left.shift()];while(left.length){let best=0;for(let i=1;i<left.length;i++)if(dist(out.at(-1),left[i])<dist(out.at(-1),left[best]))best=i;out.push(left.splice(best,1)[0]);}return out;}
function openNow(p){const hours=p.opening_hours;if(!hours||typeof hours!=="object"||!Object.keys(hours).length)return true;const now=new Date(),key=["sun","mon","tue","wed","thu","fri","sat"][now.getDay()],v=hours[key];if(!v)return false;if(v==="24h")return true;const [open,close]=String(v).split("-");if(!close)return true;const mins=(s)=>{const[h,m]=s.split(":").map(Number);return h*60+(m||0)},n=now.getHours()*60+now.getMinutes(),a=mins(open),b=mins(close);return b<a?n>=a||n<=b:n>=a&&n<=b;}

export default function PlannerClient(){
 const [data,setData]=useState(null),[err,setErr]=useState(""),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[picked,setPicked]=useState([]),[season,setSeason]=useState("all"),[filters,setFilters]=useState([]),[title,setTitle]=useState("");
 const load=()=>fetch("/api/planner").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setErr(e.message)); useEffect(load,[]);
 async function importPlace(){setBusy(true);setErr("");const r=await fetch("/api/import-place",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input})});const d=await r.json();setBusy(false);if(!r.ok)return setErr(d.error);setInput("");load();}
 const places=useMemo(()=>{let rows=data?.places||[];if(season==="summer")rows=rows.filter(p=>p.has_indoor_ac||p.has_covered_terrace||p.has_underground_parking||p.kind==="personal");if(season==="winter")rows=rows.filter(p=>p.has_outdoor_seating||p.kind==="personal");for(const f of filters){if(f==="open")rows=rows.filter(openNow);if(f==="late")rows=rows.filter(p=>p.open_late);if(f==="shisha")rows=rows.filter(p=>p.has_shisha);if(f==="prayer")rows=rows.filter(p=>p.has_prayer_room);if(f==="parking")rows=rows.filter(p=>p.parking_type||p.has_underground_parking);}return rows;},[data,season,filters]);
 const neighborhoods=useMemo(()=>Object.entries(places.reduce((a,p)=>{const k=p.neighborhood||p.city||"Saved elsewhere";a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[places]);
 const itinerary=useMemo(()=>orderStops((data?.places||[]).filter(p=>picked.includes(`${p.kind}:${p.id}`))),[data,picked]);
 function toggle(k){setPicked(x=>x.includes(k)?x.filter(y=>y!==k):x.length<4?[...x,k]:x)} function flip(f){setFilters(x=>x.includes(f)?x.filter(y=>y!==f):[...x,f])}
 async function board(){if(!title.trim()||!picked.length)return;setBusy(true);let r=await fetch("/api/boards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,isPublic:true})}),d=await r.json();if(!r.ok){setBusy(false);return setErr(d.error)}for(const key of picked){const[k,id]=key.split(":");await fetch(`/api/boards/${d.board.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add",kind:k,placeId:id})})}setTitle("");setBusy(false);load();}
 if(!data)return <p className="sub">{err||"Loading your plans…"}</p>;
 return <div className="planner-stack">
  <section className="card"><span className="eyebrow">Magic import</span><h2>Paste to map</h2><p className="sub">Paste a TikTok, Instagram link, or WhatsApp message. Weyn extracts and privately saves the place.</p><textarea value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} placeholder="Paste the link, caption, or message…"/><button className="btn primary block" disabled={busy||!input.trim()} onClick={importPlace}>{busy?"Finding it…":"Save to Want to Try"}</button></section>
  <section className="card"><div className="toggle-row"><div><strong>Ghost Mode</strong><div className="sub">Browse and save anonymously. No profile-view notifications.</div></div><input type="checkbox" checked={data.ghostMode} onChange={async e=>{const v=e.target.checked;setData({...data,ghostMode:v});await fetch("/api/planner",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ghostMode:v})})}}/></div></section>
  <section><span className="eyebrow">UAE filters</span><h2>Your saved map, smarter</h2><div className="chips"><button className={`chip ${season==="all"?"sel":""}`} onClick={()=>setSeason("all")}>All seasons</button><button className={`chip ${season==="summer"?"sel":""}`} onClick={()=>setSeason("summer")}>☀ Summer mode</button><button className={`chip ${season==="winter"?"sel":""}`} onClick={()=>setSeason("winter")}>❄ Winter mode</button>{[["open","Open now"],["late","Past 2 AM"],["shisha","Shisha & coffee"],["prayer","Prayer room"],["parking","Parking / valet"]].map(([k,l])=><button key={k} className={`chip ${filters.includes(k)?"sel":""}`} onClick={()=>flip(k)}>{l}</button>)}</div><div className="tag-row">{neighborhoods.map(([n,c])=><span className="tag-pill" key={n}>{n} · {c}</span>)}</div></section>
  <section><h2>Build a Perfect Day</h2><p className="sub">Choose 3–4 places. Weyn orders nearby stops; each stop opens in whichever map app you prefer.</p><div className="venue-list-single">{places.map(p=>{const k=`${p.kind}:${p.id}`,on=picked.includes(k);return <div className={`card ${on?"picked":""}`} key={k}><label className="toggle-row"><input type="checkbox" checked={on} onChange={()=>toggle(k)}/><span><strong>{p.name}</strong><br/><small>{p.neighborhood||p.city||"Private place"}{p.parking_type?` · ${p.parking_type}`:""}</small></span></label></div>})}</div>{itinerary.length>1&&<div className="card"><h3>Your route</h3>{itinerary.map((p,i)=><div key={`${p.kind}:${p.id}`} className="details-row"><strong>{i+1}. {p.name}</strong><MapChooser venue={p} compact/></div>)}</div>}</section>
  <section className="card"><span className="eyebrow">Burner list + trip board</span><h2>Share this plan</h2><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} placeholder="Oman Roadtrip 2026"/><button className="btn primary block" disabled={busy||!picked.length||!title.trim()} onClick={board}>Create shareable board</button>{data.boards.map(b=><div className="details-row" key={b.id}><strong>{b.title}</strong><button className="btn small ghost" onClick={()=>navigator.share?navigator.share({title:b.title,url:`${location.origin}/b/${b.share_slug}`}):navigator.clipboard.writeText(`${location.origin}/b/${b.share_slug}`)}>Share</button></div>)}</section>
  {data.curators.length>0&&<section><span className="eyebrow">Curators, not contacts</span><h2>Local tastemakers</h2><div className="venue-grid">{data.curators.map(c=><a className="card" href={`/u/${c.id}`} key={c.id}><strong>@{c.display_name}</strong><p className="sub">{c.bio||"Local Weyn curator"}</p></a>)}</div></section>}
  {err&&<div className="notice err">{err}</div>}
 </div>;
}
